version: '3'
services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus3
    restart: always
    hostname: nexus3
    ports:
      - 8081:8081
    volumes:
      - './nexus-data:/nexus-data'
    user: root
