filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

output.logstash:
  hosts: ["192.168.100.182:5044"]
output.elasticsearch:
  hosts: 'http://192.168.100.182:9200'
  username: 'elastic'
  password: 'Yuwell002223'
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
setup.kibana:
  host: 'http://192.168.100.182:5601'
