version: '3.7'
services:
  minio:
    image: 'minio/minio:latest'
    hostname: minio1
    container_name: minio1
    restart: unless-stopped
    volumes:
      - './data:/data'
      - './config:/root/.minio'
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDasdENG/bPxRfiCYEXAMPLEKEY
    command: server /data
