name: Keepalive Demo

on:
  schedule:
    # 东八区8时到24时，每小时的0分
    - cron: '0 0-16 * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - run: |
        # Heroku 保活
        wget -q https://docker-yapi.herokuapp.com/ || true
